#!/bin/sh
jsfiles=$(find . -path '*node_modules/*' -prune -o -type f -name "*.js" ! -name "*eslint*" -print)
[ -z "$jsfiles" ] && exit 0

# Prettify all staged .js files
echo "$jsfiles" | xargs ./node_modules/.bin/prettier --write

# Add back the modified/prettified files to staging
echo "$jsfiles" | xargs git add

exit 0
